---
- name: Create node exporter user
  user:
    name: nodeexp
    system: true
    shell: /usr/sbin/nologin

- name: Download node exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'
  register: download_node_exporter

- name: Extract node exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: true
    creates: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter

- name: Install node exporter binary
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/local/bin/node_exporter
    owner: nodeexp
    group: nodeexp
    mode: '0755'
    remote_src: true

- name: Deploy systemd unit
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart node exporter

- name: Ensure node exporter is running
  systemd:
    name: node_exporter
    state: started
    enabled: true
