---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Ensure site root exists
  file:
    path: "{{ site_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Deploy static site
  copy:
    src: "{{ item }}"
    dest: "{{ site_root }}/{{ item | basename }}"
    owner: www-data
    group: www-data
    mode: '0644'
  with_fileglob:
    - files/site/*

- name: Deploy nginx vhost
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/diploma.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/diploma.conf
    dest: /etc/nginx/sites-enabled/diploma.conf
    state: link
  notify: Reload nginx

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx
